Add fix to enable the CR module.
hapifhir/hapi-fhir-jpaserver-starter pull request #541
Opened 2023-05-30 19:31 UTC by chalmarm

This is to fix and enable the operation evaluate-measure to be displayed when enabling the hapi.fhir.cr_enabled flag to true in the metadata request.

2023-05-30 20:05 UTC, Capt-Mac approved these changes

2023-05-30 20:49 UTC, jmarchionatto requested changes

2023-05-30 23:21 UTC, chalmarm commented on src/main/resources/application.yaml
> +    cr_enabled: "${CR_ENABLED: false}"
Comment added.

2023-05-31 12:47 UTC, jmarchionatto approved these changes

2023-05-31 12:48 UTC, merged