Create extra-list.yaml
hapifhir/hapi-fhir-jpaserver-starter pull request #657
Opened 2024-03-06 08:59 UTC by muhammad-levi

Add ability to deploy extra manifests via the Helm chart (managed in the same file of values)

2024-03-06 18:03 UTC, jkiddo commented
@chgl can you have a look?

2024-03-08 10:43 UTC, chgl requested changes

2024-03-08 10:43 UTC, chgl commented on charts/hapi-fhir-jpaserver/templates/extra-list.yaml
This common library chart comes from bitnami, but isn't referenced in this chart so it won't work.

2024-03-08 10:43 UTC, chgl commented on charts/hapi-fhir-jpaserver/templates/extra-list.yaml
extraDeploy should be included in the values.yaml and the readme re-generated to update it

2024-04-15 20:12 UTC, jkiddo commented
Closed as deemed stale

2024-04-15 20:12 UTC, closed without merging